#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="GIT"
export ZOPEN_GIT_URL="https://github.com/git/git"
export ZOPEN_GIT_DEPS="git make m4 perl autoconf automake help2man makeinfo xz zlib openssl curl expat gettext"
export ZOPEN_BOOTSTRAP="make"
export ZOPEN_BOOTSTRAP_OPTS="configure"

export ZLIB_HOME=$HOME/zot/prod/zlib # msf - temporary

export ZOPEN_EXTRA_CPPFLAGS="-qnocsect -qnose -I\${OPENSSL_HOME}/include,\${GETTEXT_HOME}/include,\${ZLIB_HOME}/include,/usr/include/le -DNO_REGEX=NeedsStartEnd"
export ZOPEN_EXTRA_LDFLAGS="-L\${GETTEXT_HOME}/lib -L\${OPENSSL_HOME}/lib -L\${ZLIB_HOME}/lib"
